import os,sys

os.system('pkg update')
os.system('pkg upgrade')
os.system('pkg install git')
os.system('pkg install wget')
os.system('pkg install curl')
os.system('pkg install openssl')
os.system('pkg install python')
os.system('pkg install python')
os.system('pip2 install requests')
os.system('pip2 install mechanize')
os.system('pip2 install bs4')
os.system('pip2 install uncompyle6')
os.system('apt install golang')
os.system('apt install host')
os.system('apt install nano')
os.system('apt install havij')
os.system('apt install hydra')
os.system('apt install wireshark')
os.system('apt install cmatrix')
os.system('pkg install figlet')
os.system('pkg install python2')
os.system('pkg install python3')
os.system('pkg install wget -y')
os.system('pkg install python2 -y')
os.system('pkg install python2-dev -y')
os.system('apt install wireshark')
os.system('pkg install cowsay')
os.system('pkg install toilet')
os.system('pkg install ruby')
os.system('pkg install help')
os.system('gem install lolcat')
os.syztem('pkg install curl')
os.system('pkg install wgetrc')
os.system('pkg install unzip')
os.system('pkg install openssh')
os.system('pkg install tor')
os.system('pkg install git')
os.system('Pkg install nano')
os.system('pkg install tar')
os.system('pkg install zip')
os.system('pkg install net-tools')
os.system('pkg install unrar')
os.system('pkg install clang')
os.system('pkg install w3m')
os.system('pkg install proot')
os.system('pip2 install wget')
os.system('pip2 install requests')
os.system('apt install nanoos.system')
os.system('apt install php')
os.system('apt-get upgrade')
os.system('apt-get update')